
#
# Ubuntu Dockerfile
#
# https://github.com/dockerfile/ubuntu
#

# Pull base image.
FROM ubuntu:20.04

# Install.
RUN apt-get update
RUN apt-get install -y software-properties-common
RUN \
  sed -i 's/# \(.*multiverse$\)/\1/g' /etc/apt/sources.list && \
  apt-get update && \
  apt-get -y upgrade && \
  apt-get install -y build-essential && \
  apt-get install -y byobu curl git htop man unzip vim wget && \
  rm -rf /var/lib/apt/lists/*

# Add files.
ADD root/.bashrc /root/.bashrc
ADD root/.gitconfig /root/.gitconfig
ADD root/.scripts /root/.scripts

# Set environment variables.
ENV HOME /root

# Define working directory.
WORKDIR /root

RUN wget -O /usr/local/bin/dumb-init https://precise-prod.storage.googleapis.com/packages/dumb-init_1.2.2_amd64
RUN chmod +x /usr/local/bin/dumb-init

RUN wget -O/root/uam.deb https://update.u.is/downloads/uam/linux/uam-latest_amd64.deb && dpkg -i uam.deb
COPY ./start.sh ./start.sh
RUN chmod +x ./start.sh

# Define default command.
ENTRYPOINT [ "dumb-init", "--" ]
CMD ["./start.sh"]